### ISSUE TITLE
Arquitetura e Configuração

### ISSUE THREAD

**Issue by LuizLimaDev** [LuizLimaDev/front-back-montain-frontend#1]
1. Criar o projeto com Vite.
2. Configurar o ESlint.
3. Intalar as bibliotecas.
 
**Pastas**

- components
- assets
- context (estados)
- hook (logica dos componentes)
- styles (estilos globais)
- utils
- services (API)
- pages

**Bibliotecas**
- Roouter DOM
- MUI
- Axios
- React Toastfy

**Comment by Engenuis** [comment]
Foi completada a tarefa.

**Comment by LuizLimaDev** [comment]
Testado & aprovado!
