### ISSUE TITLE
Texto errado na hora de validar cpf

### ISSUE THREAD

**Issue by Amandalfs** [LuizLimaDev/front-back-montain-frontend#101]
**Descreva o bug**
Quando se coloca um cpf que ja existe esta mandando que o formato esta errado

**Reproduzir**
Etapas para reproduzir o comportamento:

1. Vá para o modal de editar
2. coloque um cpf ja existente
3. clique em aplicar
4. Veja o erro acontecer
5. Formato: XXX.XXX.XXX-XX

**Comportamento esperado**
é para aparecer um erro de cpf ja existente

**Capturas de tela**
![image](https://github.com/LuizLimaDev/front-back-mountain-frontend/assets/65101161/ef083753-edc0-4e1a-a211-e4033a4263d6)

**Comment by LuizLimaDev** [comment]
Resolvido, variavel que retorna erro modificada.
