### ISSUE TITLE
Teste das funcionalidades exigidas na sprint 02

### ISSUE THREAD

**Issue by Fernanda-Campelo** [LuizLimaDev/front-back-montain-frontend#106]
**1. Listagem do cliente**
- [x] Apenas usuários autenticados deverão conseguir acessar esta página
- [x] Ao clicar no item "clientes" do menu lateral deverá ser redirecionado para uma página com a listagem de todos os clientes cadastrados no sistema.
- [x] Deverá existir um botão "Adicionar Cliente", que ao clicado, será aberto um modal para cadastro de cliente.

Na listagem de clientes, cada item deverá mostrar:
- [x] O nome do cliente
- [x] O e-mail do cliente
- [x] O telefone do cliente
- [x] CPF
- [x] Status
- [x] Se houver alguma cobrança vencida (com status pendente e com data de vencimento anterior a data atual), deverá exibir "Inadimplente", caso contrário, deverá exibir "Em dia".
- [x] Botão de atalho, dentro da listagem, para "adicionar cobranças"
- [x] Cada nome do cliente na listagem deverá poder ser clicado de forma que ao fazê-lo, abra uma página com todos os detalhes do cliente

**2. Detalhamento do cliente**
- [x] Apenas usuários autenticados deverão conseguir acessar esta página 
- [x] Ao clicar no nome do cliente na listagem deverá abrir uma nova página com todos os detalhes do cliente clicado

A página deverá mostrar 2 cards:
- [x] O primeiro com um botão para editar cliente (ao clicar no botão, deverá abrir um modal de edição do cliente e os campos do formulário preenchidos com seus respectivos dados) e os dados do cliente:
- [x] Um título com o nome do cliente
- [x] CPF
- [x] E-mail
- [x] Telefone
- [x] Endereço completo (alguns clientes não tem endereço completo registrado pois não é obrigatório no cadastro...)
- [x] O segundo com um botão para adicionar nova cobrança e a listagem de cobranças para o cliente em questão. Cada listagem deverá mostrar: 
- [x] Identificador da Cobrança
- [x] Descrição
- [x] Data
- [x] Valor
- [x] Status

Obs:. No nosso aplicativo tem uma coluna a mais chamada de "Cobrança" com o nome do cliente, isso não é pedido no desafio e não tem no Figma:

![detalhes-cobranca-cliente-SC](https://github.com/LuizLimaDev/front-back-mountain-frontend/assets/109086907/f2efd03e-de43-4441-9132-bd4ab08095fe)

![detalhes-cobranca-cliente-figma](https://github.com/LuizLimaDev/front-back-mountain-frontend/assets/109086907/ca1058ef-2d27-416f-a314-b66c164f940a)

**3. Atualização do cliente**
- [x] Ao abrir o formulário, os dados do cliente deverão ser carregados nos respectivos campos
- [x] Para acessar este formulário de cadastro será exigido autenticação
- [x] Os dados da atualização deverão ser persistidos de maneira que possam ser consultados em qualquer momento no futuro até que sejam excluídos.

Na atualização do cliente, poderá atualizar os respectivos dados a seguir (campos com * são obrigatórios): 
- [x] Nome (*)
- [x] E-mail (*)
- [x] CPF (*)
- [x] Telefone (*)
- [x] CEP
- [x] Endereço
- [x] Complemento
- [x] Bairro
- [x] Cidade
- [x] Estado

Deverão ser informadas mensagens de erro em casos de: 
- [x] Campos obrigatórios passados em branco
Obs: Quando deixa em branco o campo de CPF, a mensagem está aparecendo em inglês:

![mensagem-ingles-cpf-editar-cliente](https://github.com/LuizLimaDev/front-back-mountain-frontend/assets/109086907/089d23f4-601c-4619-a609-b2e9b5741d0e)

- [x] E-mail informado for diferente do cliente em questão e já existir cadastrado para outro cliente
- [x] CPF informado for diferente do cliente em questão e já existir cadastrado para outro cliente
- [x] Após realizado a atualização com sucesso o usuário deverá receber uma mensagem de confirmação

**4. Cadastro de cobranças**
- [x] Para acessar este formulário de cadastro deverá ser exigida autenticação
- [x] Os dados do cadastro deverão ser persistidos de maneira que possam ser consultados em qualquer momento no futuro até que sejam excluídos.
- [x] O cadastro de cobrança deverá ser exibido em modal.

Para abrir este modal do cadastro de cobrança, o usuário deverá poder proceder de uma das duas formas: 
- [x] Clique no ícone de cadastrar cobrança, da coluna "Criar Cobrança" da listagem de clientes.
- [x] Clique no botão "+ Nova Cobrança" da listagem de cobranças da tela de detalhamento do cliente.

Campos necessários para o cadastro (* obrigatórios):
- [x] Cliente (*) -> Deverá ser um campo de texto somente leitura exibindo o nome do cliente para o qual se está cadastrando a cobrança.
- [x] Descrição (*)
- [x] Status (*)
- [x] Deverá existir duas opções: "pago" e "pendente"
- [x] Valor (*)
- [x] Vencimento (*)

Deverão ser informadas mensagens de erro em casos de:
- [x] Campos obrigatórios em branco
Obs: mensagem de erro em inglês quando deixa o campo "Valor" em branco:

![cadastro-cobranca-campo-ingles](https://github.com/LuizLimaDev/front-back-mountain-frontend/assets/109086907/74ab56ef-0f4d-4853-8cf2-bfa34159d7a7)

- [x] Após realizado o cadastro com sucesso o usuário deverá receber uma mensagem de confirmação.

**5.  Listagem de cobranças**
- [x] Apenas usuários autenticados deverão conseguir acessar esta página
- [x] Ao clicar no item "cobranças" do menu lateral, deverá ser redirecionado para uma página com a listagem de todas as cobranças cadastradas no sistema.

Na listagem de cobranças, cada item deverá mostrar: 
- [x] O identificador da cobrança
- [x] O nome do cliente
- [x] Descrição
- [x] Valor
- [x] Vencimento
- [x] Status
- [x] Pendente
- [x]  Pago
- [x] Vencido (Caso o status seja pendente e a data de vencimento for anterior a data atual)

**Comment by Engenuis** [comment]
Finalizado!
