### ISSUE TITLE
Consertar ordenação de colunas e margem de tabelas

### ISSUE THREAD

**Issue by Fernanda-Campelo** [LuizLimaDev/front-back-montain-frontend#114]
Na página de detalhes do cliente, a tabela de cobranças do cliente está com as colunas "Valor" e "Data de venc." invertidas. Também está faltando o ícone de ordenar os itens da coluna "Data de venc."

No Sem Calote:

![tabela-cobranças-detail-ordem-invertida](https://github.com/LuizLimaDev/front-back-mountain-frontend/assets/109086907/90bbfd72-f9c9-4ba9-a5c2-73891f2474ae)

No Figma:

![essa-tabela-cobranças-clientes-details](https://github.com/LuizLimaDev/front-back-mountain-frontend/assets/109086907/be5dd34c-5cc6-41bc-9a96-fe04941ef486)

Além disso, nas páginas de clientes, detalhes do cliente e cobranças, está faltando colocar uma margem de 3rem entre as tabelas e o final da página.

Ex:

![margem-ex-clientes](https://github.com/LuizLimaDev/front-back-mountain-frontend/assets/109086907/c9b19cf4-a466-4cad-86cb-752cd91e4022)

**Comment by Engenuis** [comment]
Task finalizada!
