### ISSUE TITLE
[Cobranças/Clientes] Busca e ordenação

### ISSUE THREAD

**Issue by Amandalfs** [LuizLimaDev/front-back-montain-frontend#120]
#### `Na posição de usuário do sistema, desejo buscar cobranças e clientes a partir de suas respectivas listagens.`

- <b>Critérios de aceite</b>:
  - Na listagem de cobranças deverá possibilitar a <b>ordenação dos registros</b> pelo <b>nome do cliente</b> ou <b>ID da Cobrança</b>
  - Na <b>listagem de cobranças</b> deverá existir um <b>campo de busca</b> onde permitirá buscar cobranças pelos seguintes campos:
    - Nome do cliente
    - Id da cobrança
  - Nas <b>listagens de clientes</b> deverá possibilitar a <b>ordenação</b> dos registros pelo <b>nome</b>
  - Nas <b>listagens de clientes</b> deverá existir um <b>campo de busca</b> onde permitirá buscar clientes pelos seguintes campos:
    - Nome do cliente
    - CPF do cliente
    - E-mail do cliente
  - Em caso de não retornar <b>nenhum resultado</b> uma mensagem adequada deverá ser exibida.

**Comment by Engenuis** [comment]
Finalizado!
