### ISSUE TITLE
bug: Formato e erro do CEP em Modal/NovaCobrança e Cliente/editarCliente

### ISSUE THREAD

**Issue by LuizLimaDev** [LuizLimaDev/front-back-montain-frontend#128]
Em ambos os lugares quando digitamos um CEP fora do formato não exibe erro e também não faz nada ao clicar em Aplicar.

**Verificando o erro***
1. Vá para página de 'Clientes.
2. Clique em 'Adicionar cliente'.
3. Insira um CEP com "-"(ex: 17032-569).
4. Veja o erro, não exibe mensagem de erro e nao fecha o modal.

PS: o mesmo ocorre quando clicamos em um cliente e depois em Editar Cliente.

**Imagem do erro**
![image](https://github.com/LuizLimaDev/front-back-mountain-frontend/assets/109322803/befaf4d3-79a0-4240-a62e-a194d08c0e29)

**Esperado**
Exibir a menssagem de erro da API no caso de erro. 
Barrar CEP digitados com - ou fazer o replace.

**Comment by Engenuis** [comment]
Solucionado!
