### ISSUE TITLE
Bug no cadastro de novo cliente

### ISSUE THREAD

**Issue by Fernanda-Campelo** [LuizLimaDev/front-back-montain-frontend#142]
Na página de clientes:
- Quando se tenta cadastrar um novo cliente com as informações complementares, ao dar submit no formulário, aparecem mensagens de erro nos inputs obrigatórios:

![msg-erro-2](https://github.com/LuizLimaDev/front-back-mountain-frontend/assets/109086907/9fb32499-6059-4703-8060-c2b75645a367)

Só depois de apagar os valores nesses inputs e re-escrever esses dados que o cliente é cadastrado com sucesso.

**Comment by Engenuis** [comment]
Solucionado!
