### ISSUE TITLE
[Clientes] bug: pesquisar e ordenar não funcionam

### ISSUE THREAD

**Issue by Edualct** [LuizLimaDev/front-back-montain-frontend#152]
**Descreva o bug**
Ao tentar fazer uma busca ou ordenação na página de clientes ela não faz nada.

**Reproduzir**
Etapas para reproduzir o comportamento:

Vá para 'Clientes'
Escreva algo em "pesquisa".
Clique na lupa.
Veja o erro
Clique nas setas de ordenação
Veja o erro

**Comportamento esperado**
Deveria fazer a pesquisa e a ordenação assim como o esperado.

**Comment by Amandalfs** [comment]
Por favor seja mais espeficio no que a busca e ordernacao nao esta funcionando

**Comment by LuizLimaDev** [comment]
Ja foi resolvido
