### ISSUE TITLE
[Cadastro de Clientes] bugs: Tela de cadastro com scroll

### ISSUE THREAD

**Issue by LuizLimaDev** [LuizLimaDev/front-back-montain-frontend#153]
**Descreva o bug**
Na tela cadastro existe um scroll vertical... ultrapassando o Heigth de 972px determinado no Figma

**Reproduzir**
Etapas para reproduzir o comportamento:

1. Vá para 'Cadastrar-se'.
2. Verifique e role a barra de rolagem vertical do navegador.
3. Veja o erro

![image](https://github.com/LuizLimaDev/front-back-mountain-backend/assets/109322803/6a5c3978-b0fc-4d75-bcf0-76c68563aea7)

**Comportamento esperado**
Tela sem barra de rolagem.

**Comment by Engenuis** [comment]
![image](https://github.com/LuizLimaDev/front-back-mountain-frontend/assets/87485369/3693713f-794d-4574-b6f6-a8f6a6afda1a)
No meu aqui a altura tá de 894px no Figma.
![image](https://github.com/LuizLimaDev/front-back-mountain-frontend/assets/87485369/00adb370-05e4-42c7-beff-aeb7dc049eca)
Teste em tela de 1440 x 894
![image](https://github.com/LuizLimaDev/front-back-mountain-frontend/assets/87485369/e3e728ef-8456-4f3c-837a-7ab2cf011dca)
Margin de 17.25rem (276px) de acordo com o Figma

**Comment by LuizLimaDev** [comment]
Resolvido.
