### ISSUE TITLE
[Modal Cadastro de Cliente] bugs: Console log dos dados

### ISSUE THREAD

**Issue by LuizLimaDev** [LuizLimaDev/front-back-montain-frontend#156]
**Descreva o bug**
Existe um console.log dos dados do cliente que é imprimido a cada campo preenchido, prejudicando a performance do app.

**Reproduzir**
Etapas para reproduzir o comportamento:

1. Vá para 'Clientes'.
2. Clique em 'Adicionar um cliente'.
3. Digite algum dado e clique fora do campo.
4. Veja o erro

**Comportamento esperado**
Não possuir o console.log das informações.

**Capturas de tela**
![image](https://github.com/LuizLimaDev/front-back-mountain-frontend/assets/109322803/29632a58-f387-4f2e-9a30-8d59850c13e0)

**Comment by Engenuis** [comment]
Solucionado!
