### ISSUE TITLE
[Layout do app] bugs: Erro de troca de classe Navlink

### ISSUE THREAD

**Issue by LuizLimaDev** [LuizLimaDev/front-back-montain-frontend#157]
**Descreva o bug**
Ao logar, e clicar em Cobranças.... um erro é exiibido no console.log referente a troca de classe de um componente.

**Reproduzir**
Etapas para reproduzir o comportamento:

Com o console do debuger do browser aberto:
1. Vá para 'Home'
2. Clique em 'Cobranças'
3. Veja o erro

**Comportamento esperado**
Trocar a classe para personalizar o breadcrumb sem dar erro no console.

**Capturas de tela**
![image](https://github.com/LuizLimaDev/front-back-mountain-frontend/assets/109322803/1ef49a23-aa99-4917-b8d9-ee0b78bbd510)

![image](https://github.com/LuizLimaDev/front-back-mountain-frontend/assets/109322803/56f62471-15be-477a-95f2-b74dd6eecf11)

**Comment by Engenuis** [comment]
Solucionado!
