### ISSUE TITLE
[Modal Editar Cliente] bugs: Não valida emails já existentes

### ISSUE THREAD

**Issue by LuizLimaDev** [LuizLimaDev/front-back-montain-frontend#158]
**Descreva o bug**
Quando digitamos um email existente e clicamos fora do campo... o mesmo não verifica no servidor os emails existentes ou exibe erro de email existente.

**Reproduzir**
Etapas para reproduzir o comportamento:

1. Vá para 'Clientes'
2. Clique em algum cliente
3. Clique em editar cliente e preencha com um email ja existente.
4. Clique fora do campo e Veja o erro

**Comportamento esperado**
Utilizar o hook de verificação de email existente e exibir o erro na tela com o onBlur.

**Comment by Engenuis** [comment]
Solucionado! Porém não consegui usar o hook do email.
