### ISSUE TITLE
[Modal Editar Cliente] bugs: Erros aparecendo individualmente

### ISSUE THREAD

**Issue by LuizLimaDev** [LuizLimaDev/front-back-montain-frontend#159]
**Descreva o bug**
Ao clicar em Aplicar, todos os erros existentes no formulário deveriam aparecer juntos na tela... como mostrado no Figma.

**Reproduzir**
Etapas para reproduzir o comportamento:

1. Vá para 'Página de clientes'
2. Clique em algum cliente
3. Clique em editar cliente, deixe os campos vazios ou com dados existentes e clique em Aplicar.
4. Veja o erro

**Comportamento esperado**
Exibir todos os erros juntos na tela para o cliente solucionar de uma vez só.

**Comment by Engenuis** [comment]
Solucionado!
