### ISSUE TITLE
[Exclusao de cobranças] bugs: Posicionamento do Snackbar 

### ISSUE THREAD

**Issue by LuizLimaDev** [LuizLimaDev/front-back-montain-frontend#160]
**Descreva o bug**
Tanto na tentativa de excluir cobranças que podem ou não podem ser excluidas o Snackbar esta muito abaixo na tela. Dificultando a visualização.

**Reproduzir**
Etapas para reproduzir o comportamento:

1. Vá para 'Cobranças'
2. Clique em Excluir uma cobrança
3. Veja o erro

**Comportamento esperado**
O Snackbar estar posicionado de acordo com o exemplo no Figma.

**Comment by Fernanda-Campelo** [comment]
Resolvido em PR anterior.
