### ISSUE TITLE
[Snackbar] bugs: Imagens quebradas? e posicionamento

### ISSUE THREAD

**Issue by LuizLimaDev** [LuizLimaDev/front-back-montain-frontend#162]
**Descreva o bug**
Os snackbars de conclusão de envio de informações estao aparecendo sem cores e com imagens quebradas no deploy.
Conferir a estilização

PS: Todos os Snackbar da aplicação.

**Comment by Amandalfs** [comment]
os snackbars estao normais no deploy 
![image](https://github.com/LuizLimaDev/front-back-mountain-frontend/assets/65101161/3c5e1e5d-78cf-4bf3-96b4-87fbb4a07f58)

**Comment by LuizLimaDev** [comment]
Resolvido
