### ISSUE TITLE
Erro cadastro! Formato de email inválido

### ISSUE THREAD

**Issue by LuizLimaDev** [LuizLimaDev/front-back-montain-frontend#18]
Ao cadastrar um email inválido, o Step 1 deixa passar.
Porém ao chegar no Step 2 que é enviada a conexão com a API, ela retorna o erro da imagem e não deixa o usuário prosseguir.

![image](https://github.com/LuizLimaDev/front-back-mountain-frontend/assets/109322803/edf98e3d-1608-431c-b12a-d87be2a71b34)

**Resolução**
- Bloquear já no Step1 o usuário caso ele tenha digitado um email inválido.

**Comment by Engenuis** [comment]
Problema resolvido!
