### ISSUE TITLE
Erro de limite min de caracteres na Senha - Cadastro

### ISSUE THREAD

**Issue by LuizLimaDev** [LuizLimaDev/front-back-montain-frontend#19]
Ao digitar menos de 8 caracteres, a API responde com um erro e bloqueia o usuário.
Porém este erro não está sendo exibido em tela e o usuário não pode arrumar.

![image](https://github.com/LuizLimaDev/front-back-mountain-frontend/assets/109322803/f4ef4c81-b7a2-4cfe-959c-c50bdd17ccaf)

**Resolução**
- Pegar o erro enviado pela API e exibir na tela.

**Comment by Engenuis** [comment]
Problema resolvido!
