### ISSUE TITLE
Páginas Estática - [Usuário] Cadastro do usuário

### ISSUE THREAD

**Issue by LuizLimaDev** [LuizLimaDev/front-back-montain-frontend#2]
### **Critérios de aceite**
        O cadastro deverá funcionar em formulário web que funcione em um navegador padrão
        Para acessar este formulário de cadastro não deverá ser exigida autenticação
        Os dados do cadastro deverão ser persistidos de maneira que possam ser consultados em qualquer momento no futuro até que sejam excluídos.
        O usuário poderá visualizar sua senha enquanto a escreve (Ex: Material UI Input Adornment https://mui.com/material-ui/react-text-field/
        A senha do usuário deverá ser persistida utilizando algum algoritmo de criptografia confiável

### **Campos necessários para o cadastro inicial (obrigatórios):**
        Nome do usuário (obrigatório)
        Email (obrigatório)
        Senha (obrigatório)

### **Deverão ser informadas mensagens de erro em casos de:**
        Campos obrigatórios em branco
        E-mail informado já existir cadastrado
        Após realizado o cadastro com sucesso o usuário deverá receber uma mensagem de confirmação e um botão para ser redirecionado para a página de Login.

**Comment by Engenuis** [comment]
Criação das páginas:

 - Página Estática Concluída
 - Importação da biblioteca de ícones do MUI
 - Importação das imagens em svg
 - Criação e Organização das Rotas
 - Estilização dos Componentes
 - Inserção de novos estados no contexto
 - Realização da lógica dos formulários
TODO:

Conexão com a API
