### ISSUE TITLE
Correções para implementar na página Home

### ISSUE THREAD

**Issue by Fernanda-Campelo** [LuizLimaDev/front-back-montain-frontend#34]
- Adicionar cursor pointer nos botões de editar um usuário e sair

![cursor-pointer-editar-e-sair](https://github.com/LuizLimaDev/front-back-mountain-frontend/assets/109086907/22fd9e84-bf47-4b93-ba86-7128c36160f5)

- Implementar mensagens de erro no modal de editar o cadastro do usuário (ex: 'Este campo deve ser preenchido').

![print-figma-editar-usuario](https://github.com/LuizLimaDev/front-back-mountain-frontend/assets/109086907/c52d66be-2d34-481f-ade8-2bbb02933f4c)

- Ao clicar no botão "Aplicar" do modal editar um usuário, o formulário deve ser fechado e os novos valores devem ser atualizados (ex: o nome deve atualizar sem precisar recarregar a página)

![atualizar-valores-editar-usuario](https://github.com/LuizLimaDev/front-back-mountain-frontend/assets/109086907/470fe15c-96ee-4c8d-9d2e-1882b0cd6ca9)

**Comment by LuizLimaDev** [comment]
Resolvido
