### ISSUE TITLE
[Cliente] Atualização do cliente

### ISSUE THREAD

**Issue by LuizLimaDev** [LuizLimaDev/front-back-montain-frontend#53]
### Na posição de usuário do sistema, desejo atualizar os dados de um cliente cadastrado.

**_Critérios de aceite:_**

        

- [ ] O formulário deverá ser aberto através de um clique no ícone de editar no detalhe de clientes.

        

- [ ] A atualização deverá funcionar em formulário web que funcione em um navegador padrão.

        

- [ ] Ao abrir o formulário, os dados do cliente deverão ser carregados nos respectivos campos

        

- [ ] Para acessar este formulário de cadastro será exigido autenticação

        

- [ ] Os dados da atualização deverão ser persistidos de maneira que possam ser consultados em qualquer momento no futuro até que sejam excluídos.

        

- [ ] Na atualização do cliente, poderá atualizar os respectivos dados a seguir (campos com * são obrigatórios):

            Nome (*)
            E-mail (*)
            CPF (*)
            Telefone (*)
            CEP
            Endereço
            Complemento
            Bairro
            Cidade
            Estado
        

- [ ] Deverão ser informadas mensagens de erro em casos de:

            Campos obrigatórios passados em branco
            E-mail informado for diferente do cliente em questão e já existir cadastrado para outro cliente
            CPF informado for diferente do cliente em questão e já existir cadastrado para outro cliente
        

- [ ] Após realizado a atualização com sucesso o usuário deverá receber uma mensagem de confirmação

**Comment by Engenuis** [comment]
Task concluída!
