### ISSUE TITLE
Banco de dados aceita cadastro de clientes com mesmo CPF

### ISSUE THREAD

**Issue by Engenuis** [LuizLimaDev/front-back-montain-frontend#57]
**Descreva o bug**
Ao testar cadastro de clientes notei que podem ser inseridos cpfs idênticos

**Reproduzir**
Etapas para reproduzir o comportamento:

1. Vá para Aba Clientes
2. Clique em Adicionar Cliente
3. Cadastre mais de um usuário com mesmo CPF
4. Veja o erro

**Comportamento esperado**
Espera-se uma resposta da API negando o cadastro. Preciso de uma resposta que dê para identificar o campo de erro. Dessa forma consigo remanejar o texto pro respectivo Input.

**Comment by LuizLimaDev** [comment]
Resolvido no Repo de Backend
