### ISSUE TITLE
Página Estática - [Dashboard] Configuração do Deploy

### ISSUE THREAD

**Issue by LuizLimaDev** [LuizLimaDev/front-back-montain-frontend#7]
### **Na posição de usuário do sistema, devo ser capaz de acessar o sistema através da internet, afim de usar o sistema em qualquer dispositivo com acesso a internet.**

- Critérios de aceite
        O frontend poderá ser hospedado na Netlify
        O backend e banco de dados poderá ser hospedado na Cyclic
        O frontend hospedado deverá ser integrado ao backend também hospedado

**Comment by LuizLimaDev** [comment]
TODO

- Popup de editar usuario

**Comment by Edualct** [comment]
tarefa concluida
